version: 1
disable_existing_loggers: true
formatters:
  standard:
    format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"
    datefmt: "%y.%m.%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: NOTSET
    formatter: standard
    stream: ext://sys.stdout
  logfile:
    class: logging.FileHandler
    level: NOTSET
    formatter: standard
    filename: log.txt
    mode: a
  # logfile:
  #   class: logging.handlers.RotatingFileHandler
  #   level: NOTSET
  #   formatter: standard
  #   filename: log.log
  #   maxBytes: 10000
  #   backupCount: 5
root:
  level: INFO
  handlers:
    - console
    - logfile
  propagate: yes
loggers:
  bot:
    level: NOTSET
    propagate: yes
  botsocket:
    level: NOTSET
    propagate: yes
  userlist:
    level: NOTSET
    propagate: yes
  playlist:
    level: NOTSET
    propagate: yes
  db:
    level: NOTSET
    propagate: yes
  discordbot:
    level: NOTSET
    propagate: yes
  engineio:
    level: WARNING
    propagate: yes
  socketio:
    level: WARNING
    propagate: yes
  discord:
    level: WARNING
    propagate: yes